### ISSUE TITLE
I need run larpug.js as daemon service?

### ISSUE THREAD

**Issue by maxshaw** [acidjazz/larpug#2]

**Comment by acidjazz** [comment]
@maxshaw yes, as the readme says, this is an adapter, not a rewrite.  this actually connects to the pugjs api, passing in the data needed to compile the template, and then pulls in the compiled template.  to do this the adapter checks if larpug.js is running as a daemon to connect to, otherwise launches it.  i found this methodology to be about 40x faster than running node every time we needed a template compiled.

**Comment by maxshaw** [comment]
ok, thanks for your reply.
